/*
 * To change this  license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rsa.rsasecuritychatui;

import com.client.ChatWindowUI;
import com.security.rsa.RSA;
import com.security.rsa.RSAKey;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;


/**
 * @author snehitha
 */
public class Loginform extends javax.swing.JFrame {


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jServerUriTextField;
    private javax.swing.JLabel jServerUriLabel;
    /**
     * Creates new form NewJFrame
     */
    public Loginform() {
        initComponents();
    }

    private static String convertStreamToString(InputStream is) {

        BufferedReader reader = new BufferedReader(new InputStreamReader(is));
        StringBuilder sb = new StringBuilder();

        String line = null;
        try {
            while ((line = reader.readLine()) != null) {
                sb.append(line + "\n");
            }
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            try {
                is.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        return sb.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jServerUriLabel = new javax.swing.JLabel();
        jServerUriTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 300));
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 130, 191, 28);

        jLabel1.setText("UserName:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 140, 68, 16);

        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 165, 80, 20);

        jServerUriLabel.setText("Server URI: ");
        getContentPane().add(jServerUriLabel);
        jServerUriLabel.setBounds(20, 190, 80, 20);

        getContentPane().add(jServerUriTextField);
        jServerUriTextField.setBounds(130, 190, 191, 28);
        jServerUriTextField.setText("http://127.0.0.1:4000");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(130, 160, 191, 28);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 220, 88, 29);

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(240, 220, 86, 29);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("     Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 278, 43);

        jLabel4.setText("New User(Sign Up)");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 110, 115, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/butterfly.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setToolTipText("");
        jLabel5.setMaximumSize(new java.awt.Dimension(350, 450));
        jLabel5.setMinimumSize(new java.awt.Dimension(300, 400));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 500, 380);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 290, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //  jButton2 b = new jButton2("reset");
        // jButton jButton2 = new jButton("reset");
        jTextField1.setText(null);
        jPasswordField1.setText(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


        String username = jTextField1.getText();
        char[] p = jPasswordField1.getPassword();
        String pwd = p.toString();

        // Create keys
        RSAKey key = new RSAKey();
        key.GenerateKeys();
        RSA rsa = new RSA(key);

        ChatWindowUI chatWindow = new ChatWindowUI(username, jServerUriTextField.getText(), rsa, key);
        chatWindow.setVisible(true);
        setVisible(false);
//      @todo login not implemented
//      HttpClient client = HttpClientBuilder.create().build();

//      HttpPost Post = new HttpPost("http://localhost:8089/RSASecurityChatUI/Loginform?uname="+username +"&pwd=" +pwd);
//        try
//        {
//         List<NameValuePair> nameValuePairs =  new   ArrayList<NameValuePair>(2);
//         nameValuePairs.add(new BasicNameValuePair("username",username));
//         nameValuePairs.add(new BasicNameValuePair("pwd",pwd));
//         Post.setEntity(new  UrlEncodedFormEntity(nameValuePairs));
//
//         HttpResponse  rsp = client.execute(Post);
//         HttpEntity entity = rsp.getEntity();
//        InputStream inputStream = entity.getContent();
//        String response =  convertStreamToString(inputStream);
//        System.out.println("Response from server : " + response);
//        }catch(ClientProtocolException e){
//            e.printStackTrace();
//        }catch(IOException e){
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        UserSignup usp = new UserSignup();
        usp.setLocation(380, 250);
        usp.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabel4MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    // End of variables declaration//GEN-END:variables
}
